<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Allocation" nsURI="allocation" nsPrefix="allocation">
  <eClassifiers xsi:type="ecore:EClass" name="CPS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hardwares" upperBound="-1"
        eType="#//Hardware" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="broker" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topic" upperBound="-1"
        eType="#//Topic" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yakindusm" upperBound="-1"
        eType="#//YakinduSM" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YakinduSM">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outEvents" upperBound="-1"
        eType="#//OutEvent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inEvents" upperBound="-1"
        eType="#//InEvent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="observer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hardware">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" upperBound="-1"
        eType="#//RunningInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RunningInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="yakindu" lowerBound="1"
        eType="#//YakinduSM"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clientId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="publisher" eType="#//Publisher"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subscriber" eType="#//Subscriber"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Topic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" upperBound="-1"
        eType="#//Message" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Publisher">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outevent" upperBound="-1"
        eType="#//OutEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subscriber">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inevent" upperBound="-1"
        eType="#//InEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interface" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topic" eType="#//Topic"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" eType="#//Message"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interface" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topic" eType="#//Topic"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" eType="#//Message"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
